name: coffepedia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  flutter_screenutil: ^5.0.0+2
  shared_preferences: ^2.0.8
  flutter_bloc: ^7.3.1
  bot_toast: ^4.0.1
  flutter_svg: ^0.23.0+1
  circle_checkbox: ^0.0.2+1
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.1.0
  card_swiper: ^1.0.4
  map: ^1.0.0
  badges: ^2.0.2
  meta: ^1.7.0
  equatable: ^2.0.3
  sqflite: ^2.0.1
  path_provider: ^2.0.8
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  carousel_slider: ^4.0.0
  flutter_widget_from_html: ^0.8.5
  hexcolor: ^2.0.6
  path:
  flutter_offline: ^2.1.0
  pull_to_refresh: ^2.0.0
  percent_indicator: ^4.0.0
  shimmer: ^2.0.0
  easy_debounce: ^2.0.2+1
  flutter_inappwebview: 5.3.2
  pushwoosh: ^2.2.3
  appmetrica_sdk: ^0.0.7+1
  url_launcher: ^6.0.20
  latlng: ^0.1.0












dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/CoffePediaLogo.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/langs/ar.json
    - assets/langs/en.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa_Bold_Regular.otf
          weight: 700
        - asset: assets/fonts/Nexa_Heavy_Regular.otf
          weight: 900
        - asset: assets/fonts/Nexa_Regular_Regular.otf
          weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
