///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WishlistDataCategory {
/*
{
  "id": 13,
  "order": 1,
  "slug": "Accessories",
  "icon": "http://adphp.coffepidia.com/files/accessories.png",
  "name": "Accessories"
}
*/

  int? id;
  int? order;
  String? slug;
  String? icon;
  String? name;

  WishlistDataCategory({
    this.id,
    this.order,
    this.slug,
    this.icon,
    this.name,
  });
  WishlistDataCategory.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    order = json['order']?.toInt();
    slug = json['slug']?.toString();
    icon = json['icon']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['order'] = order;
    data['slug'] = slug;
    data['icon'] = icon;
    data['name'] = name;
    return data;
  }
}

class WishlistData {
/*
{
  "id": 45,
  "description": "<p>The NS Adaptor allows the Nanopresso to use NS Capules to prepare espresso.<br />\nThe advantage of using capsules is that the coffee is mechanically ground, measured, and tamped with a higher precision than we are capable of doing by hand. There is very little left for error, so your espresso is consistent every single time.<br />\nPods are convenient, mess free and easier to clean after use.<br />\nNS Capules refers to Nespresso Original capsules and compatibles.<br />\nDimension: 66x62x62 mm, 2.60x2.44x2.44 in<br />\nWeight:130 g, 0.29 lbs</p>",
  "name": "Wacaco Nanopresso NS Adapter - Black",
  "rate": null,
  "discount": 0,
  "price_before_discount": 460,
  "flavor_id": 0,
  "region_id": 0,
  "roast_id": 0,
  "brand_id": 2,
  "vendor_id": 61,
  "image": "https://api-staging.coffepidia.com/saved_images/products/014-LD-REV1_720x.png",
  "vendor": {
    "id": 61,
    "logo": "https://api-staging.coffepidia.com/saved_images/logo/8XxG4OE8eDPhdD5cHyOFkJkr9M9b8VND8AZ9h3bn.jpg",
    "feature": [
      "Takeaway"
    ],
    "company_name": "my comamy",
    "cover_photo": "https://api-staging.coffepidia.com/saved_images/cover_photo/tVHLNO9XqmHo4CYFufWD7iZegswXTdjf0zNh4waZ.jpg",
    "description": null,
    "address": "Address English",
    "map": null
  },
  "overview": {
    "region": "",
    "brand": "Wacaco",
    "roast": "",
    "flavor": ""
  },
  "overview2": {
    "brand": "Wacaco"
  },
  "price": 460,
  "stock": 19,
  "in_wishlist": true,
  "category": {
    "id": 13,
    "order": 1,
    "slug": "Accessories",
    "icon": "http://adphp.coffepidia.com/files/accessories.png",
    "name": "Accessories"
  },
  "sub_category": ""
}
*/

  int? id;
  String? description;
  String? name;
  int? rate;
  int? discount;
  int? priceBeforeDiscount;
  int? flavorId;
  int? regionId;
  int? roastId;
  int? brandId;
  int? vendorId;
  String? image;

  int? price;
  int? stock;
  bool? inWishlist;
  WishlistDataCategory? category;
  String? subCategory;

  WishlistData({
    this.id,
    this.description,
    this.name,
    this.rate,
    this.discount,
    this.priceBeforeDiscount,
    this.flavorId,
    this.regionId,
    this.roastId,
    this.brandId,
    this.vendorId,
    this.image,
    this.price,
    this.stock,
    this.inWishlist,
    this.category,
    this.subCategory,
  });
  WishlistData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    description = json['description']?.toString();
    name = json['name']?.toString();
    rate = json['rate'] != null ? json['rate']?.toInt() : 0;
    discount = json['discount'] != null ? json['discount'].toInt() : 0;
    priceBeforeDiscount = json['price_before_discount']?.toInt();
    flavorId = json['flavor_id']?.toInt();
    regionId = json['region_id']?.toInt();
    roastId = json['roast_id']?.toInt();
    brandId = json['brand_id']?.toInt();
    vendorId = json['vendor_id']?.toInt();
    image = json['image']?.toString();

    price = json['price']?.toInt();
    stock = json['stock']?.toInt();
    inWishlist = json['in_wishlist'];
    category = (json['category'] != null)
        ? WishlistDataCategory.fromJson(json['category'])
        : null;
    subCategory = json['sub_category']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['description'] = description;
    data['name'] = name;
    data['rate'] = rate;
    data['discount'] = discount;
    data['price_before_discount'] = priceBeforeDiscount;
    data['flavor_id'] = flavorId;
    data['region_id'] = regionId;
    data['roast_id'] = roastId;
    data['brand_id'] = brandId;
    data['vendor_id'] = vendorId;
    data['image'] = image;

    data['price'] = price;
    data['stock'] = stock;
    data['in_wishlist'] = inWishlist;
    if (category != null) {
      data['category'] = category!.toJson();
    }
    data['sub_category'] = subCategory;
    return data;
  }
}

class Wishlist {
/*
{
  "data": [
    {
      "id": 45,
      "description": "<p>The NS Adaptor allows the Nanopresso to use NS Capules to prepare espresso.<br />\nThe advantage of using capsules is that the coffee is mechanically ground, measured, and tamped with a higher precision than we are capable of doing by hand. There is very little left for error, so your espresso is consistent every single time.<br />\nPods are convenient, mess free and easier to clean after use.<br />\nNS Capules refers to Nespresso Original capsules and compatibles.<br />\nDimension: 66x62x62 mm, 2.60x2.44x2.44 in<br />\nWeight:130 g, 0.29 lbs</p>",
      "name": "Wacaco Nanopresso NS Adapter - Black",
      "rate": null,
      "discount": 0,
      "price_before_discount": 460,
      "flavor_id": 0,
      "region_id": 0,
      "roast_id": 0,
      "brand_id": 2,
      "vendor_id": 61,
      "image": "https://api-staging.coffepidia.com/saved_images/products/014-LD-REV1_720x.png",
      "vendor": {
        "id": 61,
        "logo": "https://api-staging.coffepidia.com/saved_images/logo/8XxG4OE8eDPhdD5cHyOFkJkr9M9b8VND8AZ9h3bn.jpg",
        "feature": [
          "Takeaway"
        ],
        "company_name": "my comamy",
        "cover_photo": "https://api-staging.coffepidia.com/saved_images/cover_photo/tVHLNO9XqmHo4CYFufWD7iZegswXTdjf0zNh4waZ.jpg",
        "description": null,
        "address": "Address English",
        "map": null
      },
      "overview": {
        "region": "",
        "brand": "Wacaco",
        "roast": "",
        "flavor": ""
      },
      "overview2": {
        "brand": "Wacaco"
      },
      "price": 460,
      "stock": 19,
      "in_wishlist": true,
      "category": {
        "id": 13,
        "order": 1,
        "slug": "Accessories",
        "icon": "http://adphp.coffepidia.com/files/accessories.png",
        "name": "Accessories"
      },
      "sub_category": ""
    }
  ]
}
*/

  List<WishlistData?>? data;

  Wishlist({
    this.data,
  });
  Wishlist.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WishlistData>[];
      v.forEach((v) {
        arr0.add(WishlistData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
